services:
  jellyfin-newsletter:
    container_name: jellyfin-newsletter
    image: 'ghcr.io/seaweedbraincy/jellyfin-newsletter:0.10.1'
    environment:
      USER_UID: 1000
      USER_GID: 1000
      TZ: 'America/Toronto'
    volumes:
      - './config:/app/config'
    





